albedo:
    zookeeper:
        connectString: localhost:2181,localhost:2182,localhost:2183
    rpc:
        registerPath: /servers/node
        appName: hcxd-mpns-rpc-server
        hostUrl: localhost:8181



