albedo:
    zookeeper:
        connectString: localhost:2181,localhost:2182,localhost:2183
    rpc:
        registerPath: /app/node
        appName: ${spring.application.name}
        hostUrl: localhost:8183



